### ISSUE TITLE
Electra intercom 

### ISSUE THREAD

**Issue by dexter101010** [wetox-team/flipperzero-goodies#7]
Hi team. Can be Electra intercom cloned with flipper zero ?

I understand that it can be read but not cloned : 

"The tag can be read by Flipper as EM4100 but the intercom doesn’t react on its emulation (it doesn’t react at all on it, no wrong key info). I’ve tried with a few different tags (different keys) of this brand without success.

The chip inside the tag marked as CW784 HS56"

**Comment by SunnyCapt** [comment]
@dexter101010 

Your question does not apply to this repository. Please write your question in the official [discord](https://discord.com/invite/flipper) or [telegram](https://t.me/FlipperForum/) of the flipper.
