### ISSUE TITLE
Which folders go where? Asking for a noob.

### ISSUE THREAD

**Issue by WeedusFetus** [wetox-team/flipperzero-goodies#8]
Hello! I am new to Flipper and don't wanna post on the Reddit, as they like to harass when you're just trying to learn, so I figured I'd come to the source and ask. Where do these folders go in the Flipper, they look like they are just NFC, so would I just drag and drop all the contents from the zip into the NFC folder of the flipper?

**Comment by SunnyCapt** [comment]
@WeedusFetus 

| folder in zip file | folder in Flipper's SD card |
|----------|----------|
| /path/to/flipperzero-goodies_keys_release_*/ibutton    | /ibutton  2   |
| /path/to/flipperzero-goodies_keys_release_*/lfrfid    | /lfrfid   |
| /path/to/flipperzero-goodies_keys_release_*/nfc    | /nfc  |
                                                                             
Please download the zip file from [the latest release page](https://github.com/wetox-team/flipperzero-goodies/releases/latest) and read README.md

**Comment by WeedusFetus** [comment]
Yes you did! I am so sorry, I downloaded from code and not newest releases!

**Comment by klonwar** [comment]
@WeedusFetus Alternatively, if you are going to bruteforce these keys, you can convert them into fuzzer format using my [script](https://github.com/klonwar/flipperzero-goodies-to-fuzzer) and put .txt files into "ibtnfuzzer" or "rfidfuzzer" directory, respectively
